[book]
language = "en"
multilingual = false
src = "src"
title = "Taiga Design Specification"

[output.html]

[output.html.playground]
copyable = false
runnable = false

[output.katex]

[preprocessor.katex]